apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: app-ingress
    annotations:
        # Use traefik specific annotations instead of nginx
        traefik.ingress.kubernetes.io/router.entrypoints: web
        traefik.ingress.kubernetes.io/rewrite-target: /$2
spec:
    ingressClassName: traefik # Change from nginx to traefik
    rules:
        - http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend
                            port:
                                number: 80
                  - path: /api/issuance(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: issuance-service
                            port:
                                number: 80
                  - path: /api/verification(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: verification-service
                            port:
                                number: 80
